name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: get deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: build 2022
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "jupegarnica-v2022" # the name of the project on Deno Deploy
          entrypoint: "./_serve.ts" # the entrypoint to deploy
